# Generated by Django 6.0.7 on 2026-07-27 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Konşimento No')),
                ('shipment_date', models.DateField(db_index=True, verbose_name='Sevkiyat Tarihi')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('IN_TRANSIT', 'Yolda'), ('DELIVERED', 'Teslim Edildi'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('sender', models.CharField(max_length=255, verbose_name='Gönderici')),
                ('receiver', models.CharField(max_length=255, verbose_name='Alıcı')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ağırlık (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konşimento',
                'verbose_name_plural': 'Konşimentolar',
                'ordering': ['-shipment_date'],
                'indexes': [models.Index(fields=['shipment_date', 'status'], name='waybills_wa_shipmen_fe02e5_idx')],
            },
        ),
    ]
