# Generated by Django 6.0.7 on 2026-08-02 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0002_alter_waybill_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='waybill_number',
            field=models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Konşimento numarası tam 10 haneli rakamlardan oluşmalıdır.', regex='^\\d{10}$')], verbose_name='Konşimento No'),
        ),
    ]
