# Generated by Django 6.0.7 on 2026-08-25 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0003_alter_waybill_waybill_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waybill',
            options={'ordering': ['-shipment_date', '-id'], 'verbose_name': 'Konşimento', 'verbose_name_plural': 'Konşimentolar'},
        ),
        migrations.RemoveIndex(
            model_name='waybill',
            name='waybills_wa_shipmen_fe02e5_idx',
        ),
        migrations.AddField(
            model_name='waybill',
            name='collected_by',
            field=models.CharField(default='-', max_length=255, verbose_name='Toplayan'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='delivered',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Teslim Edildi'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='destination',
            field=models.CharField(default='-', max_length=255, verbose_name='Ülke - Varış Noktası'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='euro_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Euro'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kur'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='piece_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Parça'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='receiver',
            field=models.CharField(default='-', max_length=255, verbose_name='Alıcı Firma/Şahıs'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='sender',
            field=models.CharField(default='-', max_length=255, verbose_name='Gönderici Firma/Şahıs'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='shipment_date',
            field=models.DateField(db_index=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='waybill_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='AWB / Konşimento No'),
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['shipment_date', 'delivered'], name='waybills_wa_shipmen_326cad_idx'),
        ),
        migrations.RemoveField(
            model_name='waybill',
            name='status',
        ),
        migrations.RemoveField(
            model_name='waybill',
            name='weight',
        ),
    ]
