# Generated by Django 6.0.7 on 2026-08-27 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0004_alter_waybill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ağırlık (kg)'),
        ),
    ]
