# Generated by Django 6.0.7 on 2026-08-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0005_waybill_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(db_index=True, verbose_name='Kur Tarihi')),
                ('actual_bulletin_date', models.DateField(blank=True, null=True, verbose_name='Bülten Tarihi')),
                ('currency', models.CharField(default='EUR', max_length=10, verbose_name='Para Birimi')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Döviz Satış Kuru')),
                ('source', models.CharField(default='TCMB', max_length=50, verbose_name='Kaynak')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kur Önbelleği',
                'verbose_name_plural': 'Kur Önbellekleri',
                'unique_together': {('rate_date', 'currency')},
            },
        ),
    ]
