# Generated by Django 6.0.7 on 2026-08-27 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0006_exchangeratecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ödenen Tutar (TL)'),
        ),
    ]
