# Generated by Django 6.0.7 on 2026-08-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0007_waybill_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='billing_account_sales_territory',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Billing Account Sales Territory'),
        ),
    ]
